//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GekkoAssembler.Tests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionReplayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionReplayResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GekkoAssembler.Tests.ActionReplayResources", typeof(ActionReplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ; R + D-Pad Right to Load Earth Temple
        ///0x803E0D2A:
        ///!u16equal 0x0022 ; R + D-Pad Right
        ///	0x803B8742:
        ///	.u8 0x28 ; Has Medli on Boat
        ///	0x803B8755:
        ///	.u8 0x20 ; Medli in Earth Temple
        ///	0x803B8759:
        ///	.u8 1 ; Animation Set 2
        ///	.u8 0x4 ; Medli in Earth Temple Entrance
        ///	0x803B811B:
        ///	.u8 16 ; Max Magic
        ///	.u8 16 ; Magic
        ///	0x803B814A:
        ///	.u8 0x34 ; Has Deku Leaf
        ///	0x803BD248:
        ///	.str &quot;M_Dai&quot; ; Stage
        ///	.u8 0 ; Null Terminator
        ///	0x803BD250:
        ///	.u16 0 ; Entrance
        ///	.u8 0 ; Room
        ///	.s8 -1 ; Layer Override
        ///	.u8 1 ; Enable [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LoadEarthTempleInput {
            get {
                return ResourceManager.GetString("LoadEarthTempleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8A3E0D2A 00000022
        ///003B8742 00000028
        ///003B8755 00000020
        ///003B8759 00000001
        ///003B875A 00000004
        ///003B811B 00000010
        ///003B811C 00000010
        ///003B814A 00000034
        ///043BD248 4D5F4461
        ///023BD24C 00006900
        ///043BD250 000000FF
        ///003BD254 00000001
        ///00000000 40000000 ähnelt.
        /// </summary>
        internal static string LoadEarthTempleOutput {
            get {
                return ResourceManager.GetString("LoadEarthTempleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x8000645C:
        ///; Inject the function call
        ///bl 0x80A00000
        ///
        ///0x80A00000:
        ///stwu sp, -0x10 (sp)
        ///mflr r0
        ///stw r0, 0x14 (sp)	
        ///
        ///lis r4, 0x803B
        ///addi r4, r4, 0x7260
        ///addi r4, r4, 0x1000
        ///lwz r3, 0x0 (r4)
        ///addi r3, r3, 1
        ///stw r3, 0x0 (r4)
        ///addi r4, r0, 30
        ///divw r3, r3, r4
        ///addi r6, r0, 60
        ///divw r8, r3, r6
        ///mullw r4, r8, r6
        ///sub r7, r3, r4
        ///divw r5, r8, r6
        ///mullw r3, r5, r6
        ///sub r6, r8, r3
        ///lis r3, 0x8049
        ///addi r3, r3, 0x1A89
        ///lis r4, 0x80A1
        ///addi r4, r4, 0x0020
        ///crclr crb6		
        ///bl 0x80329308
        ///
        ///lwz r0, 0x14 (sp)	
        ///m [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowIGTInput {
            get {
                return ResourceManager.GetString("ShowIGTInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0400645C 489F9BA5
        ///04A00000 9421FFF0
        ///04A00004 7C0802A6
        ///04A00008 90010014
        ///04A0000C 3C80803B
        ///04A00010 38847260
        ///04A00014 38841000
        ///04A00018 80640000
        ///04A0001C 38630001
        ///04A00020 90640000
        ///04A00024 3880001E
        ///04A00028 7C6323D6
        ///04A0002C 38C0003C
        ///04A00030 7D0333D6
        ///04A00034 7C8831D6
        ///04A00038 7CE41850
        ///04A0003C 7CA833D6
        ///04A00040 7C6531D6
        ///04A00044 7CC34050
        ///04A00048 3C608049
        ///04A0004C 38631A89
        ///04A00050 3C8080A1
        ///04A00054 38840020
        ///04A00058 4CC63182
        ///04A0005C 4B9292AD
        ///04A00060 80010014
        ///04A00064 7C0803A6
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowIGTOutput {
            get {
                return ResourceManager.GetString("ShowIGTOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x80491A60:
        ///.u32 32 ; Console X Coordinate
        ///.u32 112 ; Console Y Coordinate
        ///
        ///0x80491A80:
        ///.u32 0x00000000 ; Console Background Color
        ///.u8 1 ; Console Visible
        ///
        ///0x80491A89:
        ///.str &quot;Stage: &quot; ; Line 1 Text
        ///
        ///0x80491AC6:
        ///.u8 0xFF ; Line 2 Active
        ///.str &quot;Room: &quot; ; Line 2 Text
        ///
        ///0x80491B04:
        ///.u8 0xFF ; Line 3 Active
        ///.str &quot;Entrance: &quot; ; Line 3 Text
        ///
        ///0x80491B42:
        ///.u8 0xFF ; Line 4 Active
        ///.str &quot;Layer: &quot; ; Line 4 Text
        ///
        ///0x80491BBE:
        ///.u8 0 ; No Line 5
        ///
        ///0x803B7FF4:
        ///.str &quot;%X, %X, %X&quot; ; Coordinate Format
        ///.u [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowStageInformationInput {
            get {
                return ResourceManager.GetString("ShowStageInformationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 04491A60 00000020
        ///04491A64 00000070
        ///04491A80 00000000
        ///00491A84 00000001
        ///00491A89 00000053
        ///02491A8A 00007461
        ///04491A8C 67653A20
        ///02491AC6 0000FF52
        ///04491AC8 6F6F6D3A
        ///00491ACC 00000020
        ///04491B04 FF456E74
        ///04491B08 72616E63
        ///02491B0C 0000653A
        ///00491B0E 00000020
        ///02491B42 0000FF4C
        ///04491B44 61796572
        ///02491B48 00003A20
        ///00491BBE 00000000
        ///043B7FF4 25582C20
        ///043B7FF8 25582C20
        ///043B7FFC 25580000
        ///023B8002 00002564
        ///023B8004 00000000
        ///0400645C 489F9BA5
        ///04A00000 9421FFF0
        ///04A00004 7C0802A6
        ///04A00008 90010014
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowStageInformationOutput {
            get {
                return ResourceManager.GetString("ShowStageInformationOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x803E0D2E:
        ///!u16equal 0x0004 ; D-Pad Down
        ///	0x803BD3A3:
        ///	.u8 1 ; Enable Storage
        ///!end ähnelt.
        /// </summary>
        internal static string StorageInput {
            get {
                return ResourceManager.GetString("StorageInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0A3E0D2E 00000004
        ///003BD3A3 00000001 ähnelt.
        /// </summary>
        internal static string StorageOutput {
            get {
                return ResourceManager.GetString("StorageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x80123456:
        ///.str &quot;LLLLL&quot;
        ///.u32 0xABCDABCD
        ///.u16 0xABCD
        ///.u8 0xAB
        ///.u8 0xCE
        ///.u32 0x12349999
        ///.u8 0x99 ähnelt.
        /// </summary>
        internal static string WritePatternOptimizerInput {
            get {
                return ResourceManager.GetString("WritePatternOptimizerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 02123456 00004C4C
        ///04123458 4C4C4CAB
        ///0412345C CDABCDAB
        ///04123460 CDABCE12
        ///04123464 34999999 ähnelt.
        /// </summary>
        internal static string WritePatternOptimizerOutput {
            get {
                return ResourceManager.GetString("WritePatternOptimizerOutput", resourceCulture);
            }
        }
    }
}
