//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GekkoAssembler.Tests {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionReplayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionReplayResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GekkoAssembler.Tests.ActionReplayResources", typeof(ActionReplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ; R + D-Pad Right to Load Earth Temple
        ///0x803E0D2A:
        ///!u16equal 0x0022 ; R + D-Pad Right
        ///	0x803B8742:
        ///	.u8 0x28 ; Has Medli on Boat
        ///	0x803B8755:
        ///	.u8 0x20 ; Medli in Earth Temple
        ///	0x803B8759:
        ///	.u8 1 ; Animation Set 2
        ///	.u8 0x4 ; Medli in Earth Temple Entrance
        ///	0x803B811B:
        ///	.u8 16 ; Max Magic
        ///	.u8 16 ; Magic
        ///	0x803B814A:
        ///	.u8 0x34 ; Has Deku Leaf
        ///	0x803BD248:
        ///	.str &quot;M_Dai&quot; ; Stage
        ///	.u8 0 ; Null Terminator
        ///	0x803BD250:
        ///	.u16 0 ; Entrance
        ///	.u8 0 ; Room
        ///	.s8 -1 ; Layer Override
        ///	.u8 1 ; Enable [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LoadEarthTempleInput {
            get {
                return ResourceManager.GetString("LoadEarthTempleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8A3E0D2A 00000022
        ///003B8742 00000028
        ///003B8755 00000020
        ///023B8759 00000104
        ///023B811B 00001010
        ///003B814A 00000034
        ///043BD248 4D5F4461
        ///023BD24C 00006900
        ///043BD250 000000FF
        ///003BD254 00000001
        ///00000000 40000000 ähnelt.
        /// </summary>
        internal static string LoadEarthTempleOutput {
            get {
                return ResourceManager.GetString("LoadEarthTempleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x80491A60:
        ///.u32 32 ; Console X Coordinate
        ///.u32 112 ; Console Y Coordinate
        ///
        ///0x80491A80:
        ///.u32 0x00000000 ; Console Background Color
        ///.u8 1 ; Console Visible
        ///
        ///0x80491A89:
        ///.str &quot;Stage: &quot; ; Line 1 Text
        ///
        ///0x80491AC6:
        ///.u8 0xFF ; Line 2 Active
        ///.str &quot;Room: &quot; ; Line 2 Text
        ///
        ///0x80491B04:
        ///.u8 0xFF ; Line 3 Active
        ///.str &quot;Entrance: &quot; ; Line 3 Text
        ///
        ///0x80491B42:
        ///.u8 0xFF ; Line 4 Active
        ///.str &quot;Layer: &quot; ; Line 4 Text
        ///
        ///0x80491BBE:
        ///.u8 0 ; No Line 5
        ///
        ///0x803B7FF4:
        ///.str &quot;%X, %X, %X&quot; ; Coordinate Format
        ///.u [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowStageInformationInput {
            get {
                return ResourceManager.GetString("ShowStageInformationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 04491A60 00000020
        ///04491A64 00000070
        ///04491A80 00000000
        ///00491A84 00000001
        ///04491A89 53746167
        ///02491A8D 0000653A
        ///00491A8F 00000020
        ///04491AC6 FF526F6F
        ///02491ACA 00006D3A
        ///00491ACC 00000020
        ///04491B04 FF456E74
        ///04491B08 72616E63
        ///02491B0C 0000653A
        ///00491B0E 00000020
        ///04491B42 FF4C6179
        ///04491B46 65723A20
        ///00491BBE 00000000
        ///043B7FF4 25582C20
        ///043B7FF8 25582C20
        ///043B7FFC 25580000
        ///043B8002 25640000
        ///0400645C 489F9BA5
        ///04A00000 9421FFF0
        ///04A00004 7C0802A6
        ///04A00008 90010014
        ///04A0000C 3C608049
        ///04A00010 38631A90        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ShowStageInformationOutput {
            get {
                return ResourceManager.GetString("ShowStageInformationOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0x803E0D2E:
        ///!u16equal 0x0004 ; D-Pad Down
        ///	0x803BD3A3:
        ///	.u8 1 ; Enable Storage
        ///!end ähnelt.
        /// </summary>
        internal static string StorageInput {
            get {
                return ResourceManager.GetString("StorageInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0A3E0D2E 00000004
        ///003BD3A3 00000001 ähnelt.
        /// </summary>
        internal static string StorageOutput {
            get {
                return ResourceManager.GetString("StorageOutput", resourceCulture);
            }
        }
    }
}
